### ISSUE TITLE
Eigen general_matrix_matrix_product call signature changed

### ISSUE THREAD

**Issue by sekocabas** [Columbia-Computational-X-Lab/DiffSMat#1]
When I tried to compile DiffSMat using Eigen 3.3.9, I received compilation errors regarding `general_matrix_matrix_product` calls in `DiffSMat/src/dcomplex/DComplexMatrixFunc.hpp`. 

It seems like the following issue in Eigen lead to changes in how `general_matrix_matrix_product` is called. There are now 13 parameters in struct definition, and `run` function has an extra parameter `Index resIncr`.
https://gitlab.com/libeigen/eigen/-/issues/1741

The following lines therefore need to be modified.
https://github.com/Columbia-Computational-X-Lab/DiffSMat/blob/main/src/dcomplex/DComplexMatrixFunc.hpp#L218
https://github.com/Columbia-Computational-X-Lab/DiffSMat/blob/main/src/dcomplex/DComplexMatrixFunc.hpp#L225
https://github.com/Columbia-Computational-X-Lab/DiffSMat/blob/main/src/dcomplex/DComplexMatrixFunc.hpp#L235
https://github.com/Columbia-Computational-X-Lab/DiffSMat/blob/main/src/dcomplex/DComplexMatrixFunc.hpp#L242

**Comment by 2iw31Zhv** [comment]
Hi Sekocabas,
Thanks for the issue!
It looks like an issue due to the update of Eigen library. Could you try the following first?
https://gitlab.com/libeigen/eigen/-/releases/3.3.7
I will discuss with Professor Zheng and we may fix it to comply with the updated library.

**Comment by sekocabas** [comment]
Thank you for the suggestion, I will try out the 3.3.7 version. I was not very clear in my previous post, I was able to compile using 3.3.9 by making the changes that I mentioned.

**Comment by 2iw31Zhv** [comment]
We have fixed the issue according to your suggestions and it should work now,
Thanks for letting us know!
